# Generated by Django 4.1.3 on 2022-11-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodels',
            old_name='Tanggal_Lahir',
            new_name='Lahir',
        ),
        migrations.RenameField(
            model_name='postmodels',
            old_name='Nama_Lengkap',
            new_name='Nama',
        ),
    ]
